#!/usr/bin/env python3
"""
Build offline trajectory dataset from teacher traces.

Instead of introspecting `solvers.py`, this script now expects a JSON
file of teacher trajectories (e.g. generated by gpt-oss-120b) and
converts / copies it into `offline_trajectories.json` for SFT.

Expected teacher JSON format (list of trajectories):

[
  {
    "puzzle_id": "00d62c1b",
    "steps": [
      {
        "observation": {...},   # JSON-serializable env observation
        "action": {...},        # env action dict
        "step": 0
      },
      ...
    ],
    "success": true
  },
  ...
]

Usage:
  python -m scripts.build_offline_data \\
    --teacher-traces data/gpt_oss_120b_traces.json \\
    --out data/offline_trajectories.json
"""

from __future__ import annotations
import argparse
import json
import sys
import os


def _load_teacher_traces(path: str) -> list:
    """Load teacher trajectories JSON (e.g. from gpt-oss-120b)."""
    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"Teacher traces file not found: {path}. "
            "Provide gpt-oss-120b traces JSON first."
        )
    with open(path, "r") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("Teacher traces JSON must be a list of trajectories.")
    return data


def main():
    parser = argparse.ArgumentParser(
        description="Build offline trajectories from teacher traces (gpt-oss-120b)."
    )
    parser.add_argument(
        "--teacher-traces",
        type=str,
        default="data/gpt_oss_120b_traces.json",
        help="Path to teacher traces JSON generated by gpt-oss-120b.",
    )
    parser.add_argument("--out", "-o", type=str, default="data/offline_trajectories.json")
    args = parser.parse_args()

    trajectories = _load_teacher_traces(args.teacher_traces)
    print(f"Loaded {len(trajectories)} trajectories from {args.teacher_traces}")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(trajectories, f, indent=2, default=str)
    print(f"Saved to {args.out}")


if __name__ == "__main__":
    main()
